### ISSUE TITLE
kubens displays list on direct match

### ISSUE THREAD

**Issue by slimm609** [aca/go-kubectx#3]
regular kubens changes namespace when given a name as input

kubens valid-ns
Active namespace is "valid-ns".

kubens abc
error: no namespace exists with name "abc".

your kubens displays the list with that as a search field.    

most of the time, the namespace is known and just want to switch between them quickly

**Comment by aca** [comment]
@slimm609 
Missed that one. Thanks !

**Comment by slimm609** [comment]
Awesome.  It’s much faster.  Thanks!
